---
- name: Install haproxy
  ansible.builtin.package:
    name: haproxy
    update_cache: true
  become: true
  tags:
    - haproxy

- name: Copy the config HAProxy
  ansible.builtin.template:
    src: templates/haproxy/proxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  notify: haproxy_restarted
  tags:
    - haproxy
